// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Jub_Common.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// mnemonic strength
enum JUB_Proto_Common_ENUM_MNEMONIC_STRENGTH: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case strength128 // = 0
  case strength192 // = 1
  case strength256 // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .strength128
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .strength128
    case 1: self = .strength192
    case 2: self = .strength256
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .strength128: return 0
    case .strength192: return 1
    case .strength256: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension JUB_Proto_Common_ENUM_MNEMONIC_STRENGTH: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [JUB_Proto_Common_ENUM_MNEMONIC_STRENGTH] = [
    .strength128,
    .strength192,
    .strength256,
  ]
}

#endif  // swift(>=4.2)

/// curves
enum JUB_Proto_Common_CURVES: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case secp256K1 // = 0
  case ed25519 // = 1
  case nist256P1 // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .secp256K1
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .secp256K1
    case 1: self = .ed25519
    case 2: self = .nist256P1
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .secp256K1: return 0
    case .ed25519: return 1
    case .nist256P1: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension JUB_Proto_Common_CURVES: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [JUB_Proto_Common_CURVES] = [
    .secp256K1,
    .ed25519,
    .nist256P1,
  ]
}

#endif  // swift(>=4.2)

/// bip32_path
struct JUB_Proto_Common_Bip32Path {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var change: Bool = false

  var addressIndex: UInt64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// device info
struct JUB_Proto_Common_DeviceInfo {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var sn: String = String()

  var label: String = String()

  var bleVersion: String = String()

  var firmwareVersion: String = String()

  var pinRetry: UInt32 = 0

  var pinMaxRetry: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// result with int return value
struct JUB_Proto_Common_ResultInt {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var stateCode: UInt64 = 0

  var value: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// result with string return value
struct JUB_Proto_Common_ResultString {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var stateCode: UInt64 = 0

  var value: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// result with DeviceInfo return value
struct JUB_Proto_Common_ResultAny {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var stateCode: UInt64 = 0

  var value: [SwiftProtobuf.Google_Protobuf_Any] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "JUB.Proto.Common"

extension JUB_Proto_Common_ENUM_MNEMONIC_STRENGTH: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "STRENGTH128"),
    1: .same(proto: "STRENGTH192"),
    2: .same(proto: "STRENGTH256"),
  ]
}

extension JUB_Proto_Common_CURVES: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "secp256k1"),
    1: .same(proto: "ed25519"),
    2: .same(proto: "nist256p1"),
  ]
}

extension JUB_Proto_Common_Bip32Path: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Bip32Path"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "change"),
    2: .same(proto: "addressIndex"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularBoolField(value: &self.change)
      case 2: try decoder.decodeSingularUInt64Field(value: &self.addressIndex)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.change != false {
      try visitor.visitSingularBoolField(value: self.change, fieldNumber: 1)
    }
    if self.addressIndex != 0 {
      try visitor.visitSingularUInt64Field(value: self.addressIndex, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: JUB_Proto_Common_Bip32Path, rhs: JUB_Proto_Common_Bip32Path) -> Bool {
    if lhs.change != rhs.change {return false}
    if lhs.addressIndex != rhs.addressIndex {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension JUB_Proto_Common_DeviceInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DeviceInfo"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "sn"),
    2: .same(proto: "label"),
    3: .same(proto: "bleVersion"),
    4: .same(proto: "firmwareVersion"),
    5: .same(proto: "pinRetry"),
    6: .same(proto: "pinMaxRetry"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.sn)
      case 2: try decoder.decodeSingularStringField(value: &self.label)
      case 3: try decoder.decodeSingularStringField(value: &self.bleVersion)
      case 4: try decoder.decodeSingularStringField(value: &self.firmwareVersion)
      case 5: try decoder.decodeSingularUInt32Field(value: &self.pinRetry)
      case 6: try decoder.decodeSingularUInt32Field(value: &self.pinMaxRetry)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.sn.isEmpty {
      try visitor.visitSingularStringField(value: self.sn, fieldNumber: 1)
    }
    if !self.label.isEmpty {
      try visitor.visitSingularStringField(value: self.label, fieldNumber: 2)
    }
    if !self.bleVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.bleVersion, fieldNumber: 3)
    }
    if !self.firmwareVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.firmwareVersion, fieldNumber: 4)
    }
    if self.pinRetry != 0 {
      try visitor.visitSingularUInt32Field(value: self.pinRetry, fieldNumber: 5)
    }
    if self.pinMaxRetry != 0 {
      try visitor.visitSingularUInt32Field(value: self.pinMaxRetry, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: JUB_Proto_Common_DeviceInfo, rhs: JUB_Proto_Common_DeviceInfo) -> Bool {
    if lhs.sn != rhs.sn {return false}
    if lhs.label != rhs.label {return false}
    if lhs.bleVersion != rhs.bleVersion {return false}
    if lhs.firmwareVersion != rhs.firmwareVersion {return false}
    if lhs.pinRetry != rhs.pinRetry {return false}
    if lhs.pinMaxRetry != rhs.pinMaxRetry {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension JUB_Proto_Common_ResultInt: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ResultInt"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "stateCode"),
    2: .same(proto: "value"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularUInt64Field(value: &self.stateCode)
      case 2: try decoder.decodeSingularUInt32Field(value: &self.value)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.stateCode != 0 {
      try visitor.visitSingularUInt64Field(value: self.stateCode, fieldNumber: 1)
    }
    if self.value != 0 {
      try visitor.visitSingularUInt32Field(value: self.value, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: JUB_Proto_Common_ResultInt, rhs: JUB_Proto_Common_ResultInt) -> Bool {
    if lhs.stateCode != rhs.stateCode {return false}
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension JUB_Proto_Common_ResultString: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ResultString"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "stateCode"),
    2: .same(proto: "value"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularUInt64Field(value: &self.stateCode)
      case 2: try decoder.decodeSingularStringField(value: &self.value)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.stateCode != 0 {
      try visitor.visitSingularUInt64Field(value: self.stateCode, fieldNumber: 1)
    }
    if !self.value.isEmpty {
      try visitor.visitSingularStringField(value: self.value, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: JUB_Proto_Common_ResultString, rhs: JUB_Proto_Common_ResultString) -> Bool {
    if lhs.stateCode != rhs.stateCode {return false}
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension JUB_Proto_Common_ResultAny: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ResultAny"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "stateCode"),
    2: .same(proto: "value"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularUInt64Field(value: &self.stateCode)
      case 2: try decoder.decodeRepeatedMessageField(value: &self.value)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.stateCode != 0 {
      try visitor.visitSingularUInt64Field(value: self.stateCode, fieldNumber: 1)
    }
    if !self.value.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.value, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: JUB_Proto_Common_ResultAny, rhs: JUB_Proto_Common_ResultAny) -> Bool {
    if lhs.stateCode != rhs.stateCode {return false}
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
